repos:
  - repo: "https://github.com/PyCQA/flake8"
    rev: "5.0.4"
    hooks:
      - id: "flake8"
        name: "Python: analysis"

  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.991"
    hooks:
      - id: "mypy"
        name: "Python: types"
        additional_dependencies:
          - "types-all"

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: [ "--profile", "black"]
